# Generated by Django 5.1.15 on 2026-08-23 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id_raw', models.CharField(db_index=True, max_length=100)),
                ('result', models.CharField(choices=[('ok', 'Entrada autorizada'), ('already_entered', 'Já tinha entrado'), ('not_paid', 'Pagamento pendente'), ('not_found', 'Bilhete não encontrado'), ('invalid_qr', 'QR inválido')], max_length=20)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('raw_qr', models.CharField(blank=True, max_length=255)),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.CharField(editable=False, max_length=40, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('valid', 'Válido'), ('cancelled', 'Cancelado'), ('expired', 'Expirado')], default='valid', max_length=20)),
                ('payment', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('failed', 'Falhou'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=40)),
                ('entered', models.BooleanField(default=False)),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_tickets', to=settings.AUTH_USER_MODEL)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalog.price')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('succeeded', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='ticketing.ticket')),
            ],
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['payment', 'expires_at'], name='ticketing_t_payment_d126a9_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['phone'], name='ticketing_t_phone_82ad82_idx'),
        ),
    ]
