# Generated by Django 5.1.15 on 2026-08-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='checkout_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='provider',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='ticket',
            name='provider_charge_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
