# Generated by Django 5.1.15 on 2026-08-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_ticket_checkout_url_ticket_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ticket',
            name='currency',
            field=models.CharField(default='MZN', max_length=3),
        ),
    ]
