# Generated by Django 5.2.17 on 2026-09-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0005_ticket_external_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="payment",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("paid", "Pago"),
                    ("failed", "Falhou"),
                    ("refunded", "Reembolsado"),
                    ("invited", "Convite"),
                    ("review", "Em revisão"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
