# Generated by Django 5.2.17 on 2026-09-28 11:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0006_alter_ticket_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("ticket.paid", "Bilhete pago"),
                            ("ticket.refunded", "Bilhete reembolsado"),
                        ],
                        max_length=30,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("gave_up_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_deliveries",
                        to="ticketing.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["next_attempt_at"],
                "indexes": [
                    models.Index(
                        fields=["delivered_at", "gave_up_at", "next_attempt_at"],
                        name="ticketing_p_deliver_51fcfa_idx",
                    )
                ],
            },
        ),
    ]
