# Generated by Django 5.2.17 on 2026-09-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0007_partnerdelivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="test_mode",
            field=models.BooleanField(default=False),
        ),
    ]
