# Generated by Django 5.2.17 on 2026-09-30 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
        ("ticketing", "0008_ticket_test_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ticket",
            name="uniq_ticket_partner_external_reference",
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("external_reference", ""), _negated=True),
                    ("payment__in", ["pending", "paid"]),
                ),
                fields=("issued_to", "external_reference"),
                name="uniq_ticket_partner_external_reference",
            ),
        ),
    ]
