# Generated by Django 5.2.17 on 2026-09-30 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_event_confirmation_deadline_event_registration_mode"),
        ("ticketing", "0009_external_reference_constraint_alive_only"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ticket",
            name="uniq_ticket_partner_external_reference",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="payment",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("paid", "Pago"),
                    ("failed", "Falhou"),
                    ("refunded", "Reembolsado"),
                    ("invited", "Convite"),
                    ("review", "Em revisão"),
                    ("preregistered", "Pré-inscrito"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("external_reference", ""), _negated=True),
                    ("payment__in", ["pending", "paid", "preregistered"]),
                ),
                fields=("issued_to", "external_reference"),
                name="uniq_ticket_partner_external_reference",
            ),
        ),
    ]
