# Generated by Django 5.2.17 on 2026-10-07 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0002_webhookendpoint"),
        (
            "ticketing",
            "0010_remove_ticket_uniq_ticket_partner_external_reference_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerdelivery",
            name="endpoint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="partners.webhookendpoint",
            ),
        ),
    ]
