# Generated by Django 5.1.15 on 2026-08-23 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='price',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.event'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'date'], name='catalog_eve_status_87bdd7_idx'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_reserved__lte', models.F('quantity_total'))), name='price_no_oversell'),
        ),
    ]
