# Generated by Django 5.2.17 on 2026-09-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="confirmation_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Limite para confirmar presença (só em pré-inscrição).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_mode",
            field=models.CharField(
                choices=[
                    ("direct", "Inscrição directa (compra/pagamento)"),
                    ("preregistration", "Pré-inscrição + confirmação de presença"),
                ],
                default="direct",
                max_length=20,
            ),
        ),
    ]
