# Generated by Django 5.2.17 on 2026-09-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_event_confirmation_deadline_event_registration_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="confirmation_opens_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Quando a confirmação de presença abre. Vazio = ainda fechada (a organização decide quando abrir, ex.: 2 dias antes do evento).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="confirmation_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Limite para confirmar presença (só em pré-inscrição); as vagas não confirmadas são libertadas nesse momento.",
                null=True,
            ),
        ),
    ]
