# Generated by Django 5.2.17 on 2026-09-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_event_confirmation_opens_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="offers_shirts",
            field=models.BooleanField(
                default=False,
                help_text="O evento tem camisetes (o participante escolhe o tamanho).",
            ),
        ),
    ]
